export const doctorPatientSummaries = [{
  patientId: 'PT-1042',
  name: 'Selam Bekele',
  age: 32,
  gender: 'Female',
  bloodType: 'O+',
  hospital: 'Black Lion Hospital',
  activeProblem: 'Hypertension exacerbation and shortness of breath follow-up',
  reasonForVisit: 'Post-acute review after emergency outpatient evaluation',
  riskLevel: 'Moderate',
  primaryDoctor: 'Dr. Sara Mekonnen',
  lastEncounter: '2026-05-28 · Emergency outpatient follow-up',
  currentMedications: ['Amlodipine 5 mg once daily', 'Home BP log review'],
  prominentAllergies: ['Penicillin'],
  latestVitals: {
    bloodPressure: '148/92 mmHg',
    heartRate: '84 bpm',
    weight: '63 kg',
    temperature: '37.1°C'
  },
  recommendedNextAction: 'Continue weekly blood pressure monitoring and review medication adherence at next clinic visit.',
  latestVisit: '2026-05-28 · Emergency outpatient follow-up',
  latestDiagnosis: 'Hypertension exacerbation',
  latestPrescription: 'Amlodipine 5 mg once daily',
  latestLabResult: 'CBC normal; blood pressure trend improving',
  allergies: ['Penicillin'],
  chronicConditions: ['Hypertension']
}, {
  patientId: 'PT-1087',
  name: 'Abel Tadesse',
  age: 47,
  gender: 'Male',
  bloodType: 'A-',
  hospital: 'St. Paul Millennium Medical College',
  activeProblem: 'Stable ischemic heart disease with chronic medication review',
  reasonForVisit: 'Cardiology follow-up for chronic disease management',
  riskLevel: 'Low',
  primaryDoctor: 'Dr. Yared Bekele',
  lastEncounter: '2026-05-24 · Cardiology review',
  currentMedications: ['Atorvastatin 20 mg nightly', 'Aspirin 81 mg daily'],
  prominentAllergies: ['Sulfa'],
  latestVitals: {
    bloodPressure: '132/84 mmHg',
    heartRate: '76 bpm',
    weight: '71 kg',
    temperature: '36.9°C'
  },
  recommendedNextAction: 'Maintain current therapy and schedule the next lipid panel review.',
  latestVisit: '2026-05-24 · Cardiology review',
  latestDiagnosis: 'Stable ischemic heart disease',
  latestPrescription: 'Atorvastatin 20 mg nightly',
  latestLabResult: 'Lipid panel within target range',
  allergies: ['Sulfa'],
  chronicConditions: ['Chronic heart disease', 'Diabetes']
}, {
  patientId: 'PT-1099',
  name: 'Mekdes Ali',
  age: 29,
  gender: 'Female',
  bloodType: 'B+',
  hospital: 'Black Lion Hospital',
  activeProblem: 'Acute respiratory monitoring and asthma follow-up',
  reasonForVisit: 'Breathing review after recent symptom flare',
  riskLevel: 'Moderate',
  primaryDoctor: 'Dr. Hana Bekele',
  lastEncounter: '2026-05-21 · Respiratory monitoring',
  currentMedications: ['Salbutamol inhaler as needed', 'Inhaled steroid maintenance'],
  prominentAllergies: ['Dust'],
  latestVitals: {
    bloodPressure: '124/80 mmHg',
    heartRate: '92 bpm',
    weight: '58 kg',
    temperature: '37.0°C'
  },
  recommendedNextAction: 'Reassess inhaler technique and monitor oxygen saturation trends.',
  latestVisit: '2026-05-21 · Respiratory monitoring',
  latestDiagnosis: 'Acute respiratory monitoring',
  latestPrescription: 'Salbutamol inhaler as needed',
  latestLabResult: 'Oxygen saturation trending upward',
  allergies: ['Dust'],
  chronicConditions: ['Asthma']
}, {
  patientId: 'PT-1105',
  name: 'Daniel Bekele',
  age: 54,
  gender: 'Male',
  bloodType: 'AB+',
  hospital: 'Yekatit 12 Hospital',
  activeProblem: 'Type 2 diabetes management and glucose trend review',
  reasonForVisit: 'Routine follow-up for diabetes control and medication adherence',
  riskLevel: 'Moderate',
  primaryDoctor: 'Dr. Selamawit Assefa',
  lastEncounter: '2026-05-18 · Diabetes review',
  currentMedications: ['Metformin 500 mg twice daily', 'Glucose monitoring log'],
  prominentAllergies: ['Latex'],
  latestVitals: {
    bloodPressure: '130/82 mmHg',
    heartRate: '78 bpm',
    weight: '72 kg',
    temperature: '36.8°C'
  },
  recommendedNextAction: 'Continue glucose monitoring and review lifestyle adherence at the next check-in.',
  latestVisit: '2026-05-18 · Diabetes review',
  latestDiagnosis: 'Type 2 diabetes management',
  latestPrescription: 'Metformin 500 mg twice daily',
  latestLabResult: 'Glucose trend stable',
  allergies: ['Latex'],
  chronicConditions: ['Type 2 diabetes']
}, {
  patientId: 'PT-1121',
  name: 'Tigist Worku',
  age: 41,
  gender: 'Female',
  bloodType: 'O-',
  hospital: 'Yekatit 12 Hospital',
  activeProblem: 'Post-cardiac rehabilitation conditioning and blood pressure stability',
  reasonForVisit: 'Rehabilitation follow-up after recent cardiac care',
  riskLevel: 'Low',
  primaryDoctor: 'Dr. Alemayehu Worku',
  lastEncounter: '2026-05-16 · Cardiac rehab check-in',
  currentMedications: ['Beta-blocker maintenance', 'Exercise and diet adherence plan'],
  prominentAllergies: ['Shellfish'],
  latestVitals: {
    bloodPressure: '126/78 mmHg',
    heartRate: '72 bpm',
    weight: '68 kg',
    temperature: '36.7°C'
  },
  recommendedNextAction: 'Continue rehabilitation pacing and review blood pressure stability next week.',
  latestVisit: '2026-05-16 · Cardiac rehab check-in',
  latestDiagnosis: 'Post-cardiac rehab conditioning',
  latestPrescription: 'Beta-blocker maintenance',
  latestLabResult: 'Heart rate and blood pressure stable',
  allergies: ['Shellfish'],
  chronicConditions: ['Cardiac rehabilitation']
}, {
  patientId: 'PT-1134',
  name: 'Yonas Habte',
  age: 36,
  gender: 'Male',
  bloodType: 'A+',
  hospital: 'St. Paul Millennium Medical College',
  activeProblem: 'Orthopedic recovery and pain management follow-up',
  reasonForVisit: 'Mobility review after recent orthopedic treatment',
  riskLevel: 'Low',
  primaryDoctor: 'Dr. Bekele Lemma',
  lastEncounter: '2026-05-10 · Orthopedic recovery review',
  currentMedications: ['Pain management support', 'Mobility exercise plan'],
  prominentAllergies: ['Ibuprofen'],
  latestVitals: {
    bloodPressure: '120/76 mmHg',
    heartRate: '74 bpm',
    weight: '75 kg',
    temperature: '36.8°C'
  },
  recommendedNextAction: 'Continue mobility support and schedule the next orthopedic review.',
  latestVisit: '2026-05-10 · Orthopedic recovery review',
  latestDiagnosis: 'Orthopedic recovery follow-up',
  latestPrescription: 'Pain management support',
  latestLabResult: 'Mobility assessment improving',
  allergies: ['Ibuprofen'],
  chronicConditions: ['Orthopedic recovery']
}];
export function getDoctorPatientSummary(patientId) {
  return doctorPatientSummaries.find(patient => patient.patientId === patientId) ?? null;
}
